apiVersion: workflow.example.com/v1
kind: WorkflowTask
metadata:
  name: fetch-posts
  namespace: default
spec:
  type: http
  description: Fetches posts for a given user ID
  request:
    url: "https://jsonplaceholder.typicode.com/posts?userId={{input.userId}}"
    method: GET
    headers:
      Accept: "application/json"
  inputSchema:
    type: object
    properties:
      userId:
        type: string
        description: The user ID to fetch posts for
    required:
      - userId
  outputSchema:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        title:
          type: string
        body:
          type: string
