apiVersion: workflow.example.com/v1
kind: Workflow
metadata:
  name: template-space-info
  namespace: default
  annotations:
    workflow.example.com/template: "true"
    workflow.example.com/category: "api-composition"
    workflow.example.com/difficulty: "beginner"
    workflow.example.com/tags: "http,api,parallel,fun,no-input"
    workflow.example.com/estimatedTime: "5"
spec:
  description: "🎯 TEMPLATE: Fun space facts API composition - Fetch astronaut info, ISS location, and a dad joke in parallel. Perfect beginner example showing parallel HTTP calls with no input required and creative output mapping."
  input: {}
  tasks:
    - id: get-astronauts
      taskRef: fetch-astronauts
      input: {}
    - id: get-iss-location
      taskRef: fetch-iss-location
      input: {}
    - id: get-joke
      taskRef: fetch-dad-joke
      input: {}
  output:
    astronautCount: "{{tasks.get-astronauts.output.number}}"
    astronautNames: "{{tasks.get-astronauts.output.people}}"
    issLatitude: "{{tasks.get-iss-location.output.iss_position.latitude}}"
    issLongitude: "{{tasks.get-iss-location.output.iss_position.longitude}}"
    dadJoke: "{{tasks.get-joke.output.joke}}"
    funFact: "There are currently {{tasks.get-astronauts.output.number}} people in space!"
