# Workflow 2: User Login
# Uses shared task: validate-user
apiVersion: workflow.example.com/v1
kind: Workflow
metadata:
  name: user-login
  namespace: default
  labels:
    workflow.io/demo: "blast-radius"
spec:
  description: "User authentication flow - uses validate-user task"
  input:
    email:
      type: string
      required: true
    password:
      type: string
      required: true
  tasks:
    - id: validate
      taskRef: validate-user
      input:
        email: "{{input.email}}"
        validationContext: "login"
  output:
    message: "Login flow completed"
