// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowCore.Data;

#nullable disable

namespace WorkflowCore.Data.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20251127145255_AddDurationTrendsIndexes")]
    partial class AddDurationTrendsIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowCore.Models.ExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ExecutionRecords_Status");

                    b.HasIndex("WorkflowName", "StartedAt", "Status")
                        .HasDatabaseName("IX_ExecutionRecords_WorkflowName_StartedAt_Status");

                    b.ToTable("ExecutionRecords");
                });

            modelBuilder.Entity("WorkflowCore.Models.TaskExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.Property<string>("TaskRef")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("TaskRef", "StartedAt", "Status")
                        .HasDatabaseName("IX_TaskExecutionRecords_TaskRef_StartedAt_Status");

                    b.ToTable("TaskExecutionRecords");
                });

            modelBuilder.Entity("WorkflowCore.Models.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("VersionHash")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_WorkflowVersions_CreatedAt");

                    b.HasIndex("WorkflowName")
                        .HasDatabaseName("IX_WorkflowVersions_WorkflowName");

                    b.ToTable("WorkflowVersions");
                });

            modelBuilder.Entity("WorkflowCore.Models.TaskExecutionRecord", b =>
                {
                    b.HasOne("WorkflowCore.Models.ExecutionRecord", "ExecutionRecord")
                        .WithMany("TaskExecutionRecords")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRecord");
                });

            modelBuilder.Entity("WorkflowCore.Models.ExecutionRecord", b =>
                {
                    b.Navigation("TaskExecutionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
