// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowCore.Data;

#nullable disable

namespace WorkflowCore.Data.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20251208080713_AddHttpMethodAndResolvedUrlToTaskExecutionRecord")]
    partial class AddHttpMethodAndResolvedUrlToTaskExecutionRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowCore.Data.ErrorQualityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CriteriaBreakdownJson")
                        .HasColumnType("text")
                        .HasColumnName("criteria_breakdown");

                    b.Property<int>("CriteriaMet")
                        .HasColumnType("integer")
                        .HasColumnName("criteria_met");

                    b.Property<int>("CriteriaMissing")
                        .HasColumnType("integer")
                        .HasColumnName("criteria_missing");

                    b.Property<string>("ErrorBody")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_body");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("ImprovementTipsJson")
                        .HasColumnType("text")
                        .HasColumnName("improvement_tips");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<Guid?>("TaskExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_execution_id");

                    b.Property<string>("TaskId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("task_ref");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workflow_name");

                    b.HasKey("Id");

                    b.ToTable("error_quality_records");
                });

            modelBuilder.Entity("WorkflowCore.Models.ExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("GraphBuildDuration")
                        .HasColumnType("interval");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ExecutionRecords_Status");

                    b.HasIndex("WorkflowName", "StartedAt", "Status")
                        .HasDatabaseName("IX_ExecutionRecords_WorkflowName_StartedAt_Status");

                    b.ToTable("ExecutionRecords");
                });

            modelBuilder.Entity("WorkflowCore.Models.LabelUsageStatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LabelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LabelValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LabelType", "LabelValue", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("UQ_LabelUsageStats");

                    b.ToTable("LabelUsageStats");
                });

            modelBuilder.Entity("WorkflowCore.Models.TaskExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("ErrorInfo")
                        .HasColumnType("text");

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<string>("ResolvedUrl")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.Property<string>("TaskRef")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("TaskRef", "StartedAt", "Status")
                        .HasDatabaseName("IX_TaskExecutionRecords_TaskRef_StartedAt_Status");

                    b.ToTable("TaskExecutionRecords");
                });

            modelBuilder.Entity("WorkflowCore.Models.TaskLabelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskName", "Namespace")
                        .IsUnique()
                        .HasDatabaseName("UQ_TaskLabels_Name_Namespace");

                    b.ToTable("TaskLabels");
                });

            modelBuilder.Entity("WorkflowCore.Models.TaskStatisticsSummary", b =>
                {
                    b.Property<string>("TaskRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("AverageDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double precision");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalExecutions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TaskRef");

                    b.ToTable("TaskStatisticsSummaries");
                });

            modelBuilder.Entity("WorkflowCore.Models.WorkflowLabelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("VersionHash")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowName", "Namespace")
                        .IsUnique()
                        .HasDatabaseName("UQ_WorkflowLabels_Name_Namespace");

                    b.ToTable("WorkflowLabels");
                });

            modelBuilder.Entity("WorkflowCore.Models.WorkflowStatisticsSummary", b =>
                {
                    b.Property<string>("WorkflowName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("AverageDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double precision");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalExecutions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkflowName");

                    b.ToTable("WorkflowStatisticsSummaries");
                });

            modelBuilder.Entity("WorkflowCore.Models.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("VersionHash")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_WorkflowVersions_CreatedAt");

                    b.HasIndex("WorkflowName")
                        .HasDatabaseName("IX_WorkflowVersions_WorkflowName");

                    b.ToTable("WorkflowVersions");
                });

            modelBuilder.Entity("WorkflowCore.Models.TaskExecutionRecord", b =>
                {
                    b.HasOne("WorkflowCore.Models.ExecutionRecord", "ExecutionRecord")
                        .WithMany("TaskExecutionRecords")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRecord");
                });

            modelBuilder.Entity("WorkflowCore.Models.ExecutionRecord", b =>
                {
                    b.Navigation("TaskExecutionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
